export const UPDATE_SEARCH_EXPRESSION = 'UPDATE_SEARCH_EXPRESSION';
export const UPDATE_SEARCH_BY = 'UPDATE_SEARCH_BY';
export const TRIGGER_SEARCH = 'TRIGGER_SEARCH';

export const SEARCH_BY = {
	TITLE: 'TITLE',
	GENRE: 'GENRE',
};